# -*- coding: utf-8 -*-
"""Palindrome Checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWDRaY3qN6t_QoZQb7TL2OsudYJExMOM
"""



"""## Palindrome Checker

I am writing a program to determine if a given word or sentence is a palindrome. The program will ignore spaces, punctuation, and be case-insensitive. I will use a `for` loop to compare characters from the beginning and end of the string.
"""

import re

def clean_string(input_string):
    """
    Cleans the input string by removing non-alphanumeric characters and converting it to lowercase.
    """
    # Use regex to remove non-alphanumeric characters and convert to lowercase
    cleaned_string = re.sub(r'[^a-zA-Z0-9]', '', input_string).lower()
    return cleaned_string

def is_palindrome_while(input_string):
    """
    Checks if the input string is a palindrome using a while loop.
    """
    cleaned_string = clean_string(input_string)
    left = 0
    right = len(cleaned_string) - 1

    while left < right:
        if cleaned_string[left] != cleaned_string[right]:
            return False
        left += 1
        right -= 1
    return True

def is_palindrome_for(input_string):
    """
    Checks if the input string is a palindrome using a for loop.
    """
    cleaned_string = clean_string(input_string)
    length = len(cleaned_string)

    for i in range(length // 2):
        if cleaned_string[i] != cleaned_string[length - 1 - i]:
            return False
    return True

# Test cases
test_cases = [
    "A man, a plan, a canal, Panama",
    "Racecar",
    "No lemon, no melon",
    "Hello, World!",
    "12321",
    "123abc",
    "Was it a car or a cat I saw?",
    "Step on no pets"
]

# Testing the functions
for test in test_cases:
    print(f"Test: '{test}'")
    print(f"is_palindrome_while: {is_palindrome_while(test)}")
    print(f"is_palindrome_for: {is_palindrome_for(test)}")
    print()

